# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import modelx_pb2 as modelx__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in modelx_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ModelxStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/model.Modelx/Ping',
                request_serializer=modelx__pb2.PingRequest.SerializeToString,
                response_deserializer=modelx__pb2.PongReply.FromString,
                _registered_method=True)
        self.GenEmbedding = channel.unary_unary(
                '/model.Modelx/GenEmbedding',
                request_serializer=modelx__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=modelx__pb2.EmbeddingReply.FromString,
                _registered_method=True)
        self.GenEmbeddingList = channel.unary_unary(
                '/model.Modelx/GenEmbeddingList',
                request_serializer=modelx__pb2.EmbeddingListRequest.SerializeToString,
                response_deserializer=modelx__pb2.EmbeddingListReply.FromString,
                _registered_method=True)
        self.CalcSimilarityScore = channel.unary_unary(
                '/model.Modelx/CalcSimilarityScore',
                request_serializer=modelx__pb2.SimilarityRequest.SerializeToString,
                response_deserializer=modelx__pb2.SimilarityReply.FromString,
                _registered_method=True)
        self.ExtractKeywords = channel.unary_unary(
                '/model.Modelx/ExtractKeywords',
                request_serializer=modelx__pb2.ExtractKeywordsRequest.SerializeToString,
                response_deserializer=modelx__pb2.ExtractKeywordsReply.FromString,
                _registered_method=True)


class ModelxServicer(object):
    """The greeting service definition.
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenEmbedding(self, request, context):
        """generate embedding vector for passed sentence.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenEmbeddingList(self, request, context):
        """bulk generate embedding vectors.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcSimilarityScore(self, request, context):
        """calc similarity score for sentence.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractKeywords(self, request, context):
        """extract keywords from input.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=modelx__pb2.PingRequest.FromString,
                    response_serializer=modelx__pb2.PongReply.SerializeToString,
            ),
            'GenEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenEmbedding,
                    request_deserializer=modelx__pb2.EmbeddingRequest.FromString,
                    response_serializer=modelx__pb2.EmbeddingReply.SerializeToString,
            ),
            'GenEmbeddingList': grpc.unary_unary_rpc_method_handler(
                    servicer.GenEmbeddingList,
                    request_deserializer=modelx__pb2.EmbeddingListRequest.FromString,
                    response_serializer=modelx__pb2.EmbeddingListReply.SerializeToString,
            ),
            'CalcSimilarityScore': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcSimilarityScore,
                    request_deserializer=modelx__pb2.SimilarityRequest.FromString,
                    response_serializer=modelx__pb2.SimilarityReply.SerializeToString,
            ),
            'ExtractKeywords': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractKeywords,
                    request_deserializer=modelx__pb2.ExtractKeywordsRequest.FromString,
                    response_serializer=modelx__pb2.ExtractKeywordsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.Modelx', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model.Modelx', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Modelx(object):
    """The greeting service definition.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.Modelx/Ping',
            modelx__pb2.PingRequest.SerializeToString,
            modelx__pb2.PongReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.Modelx/GenEmbedding',
            modelx__pb2.EmbeddingRequest.SerializeToString,
            modelx__pb2.EmbeddingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenEmbeddingList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.Modelx/GenEmbeddingList',
            modelx__pb2.EmbeddingListRequest.SerializeToString,
            modelx__pb2.EmbeddingListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcSimilarityScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.Modelx/CalcSimilarityScore',
            modelx__pb2.SimilarityRequest.SerializeToString,
            modelx__pb2.SimilarityReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractKeywords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.Modelx/ExtractKeywords',
            modelx__pb2.ExtractKeywordsRequest.SerializeToString,
            modelx__pb2.ExtractKeywordsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
