# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modelx.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmodelx.proto\x12\x05model\"\r\n\x0bPingRequest\"\x19\n\tPongReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\x0e\x45mbeddingReply\x12\x11\n\tembedding\x18\x01 \x01(\t\")\n\x14\x45mbeddingListRequest\x12\x11\n\ttext_list\x18\x01 \x03(\t\",\n\x12\x45mbeddingListReply\x12\x16\n\x0e\x65mbedding_list\x18\x01 \x03(\t\">\n\x11SimilarityRequest\x12\x13\n\x0bsource_text\x18\x01 \x01(\t\x12\x14\n\x0ctarget_texts\x18\x02 \x03(\t\"!\n\x0fSimilarityReply\x12\x0e\n\x06scores\x18\x01 \x03(\x01\x32\x93\x02\n\x06Modelx\x12.\n\x04Ping\x12\x12.model.PingRequest\x1a\x10.model.PongReply\"\x00\x12@\n\x0cGenEmbedding\x12\x17.model.EmbeddingRequest\x1a\x15.model.EmbeddingReply\"\x00\x12L\n\x10GenEmbeddingList\x12\x1b.model.EmbeddingListRequest\x1a\x19.model.EmbeddingListReply\"\x00\x12I\n\x13\x43\x61lcSimilarityScore\x12\x18.model.SimilarityRequest\x1a\x16.model.SimilarityReply\"\x00\x42\x0bZ\t./;modelxb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modelx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./;modelx'
  _globals['_PINGREQUEST']._serialized_start=23
  _globals['_PINGREQUEST']._serialized_end=36
  _globals['_PONGREPLY']._serialized_start=38
  _globals['_PONGREPLY']._serialized_end=63
  _globals['_EMBEDDINGREQUEST']._serialized_start=65
  _globals['_EMBEDDINGREQUEST']._serialized_end=97
  _globals['_EMBEDDINGREPLY']._serialized_start=99
  _globals['_EMBEDDINGREPLY']._serialized_end=134
  _globals['_EMBEDDINGLISTREQUEST']._serialized_start=136
  _globals['_EMBEDDINGLISTREQUEST']._serialized_end=177
  _globals['_EMBEDDINGLISTREPLY']._serialized_start=179
  _globals['_EMBEDDINGLISTREPLY']._serialized_end=223
  _globals['_SIMILARITYREQUEST']._serialized_start=225
  _globals['_SIMILARITYREQUEST']._serialized_end=287
  _globals['_SIMILARITYREPLY']._serialized_start=289
  _globals['_SIMILARITYREPLY']._serialized_end=322
  _globals['_MODELX']._serialized_start=325
  _globals['_MODELX']._serialized_end=600
# @@protoc_insertion_point(module_scope)
